name: "Heroku Git Push"
description: "Push code to Heroku deployments"
inputs:
  email:
    description: "Email associated with Heroku for pushing"
    required: true
  api_key:
    description: "Heroku API key"
    required: true
  app_names:
    description: "Names of the apps on Heroku"
    required: true
  push_timeout:
    description: "Amount of time (ms) to wait for Heroku push to complete"
    required: false
    default: "5000"

runs:
  using: "node16"
  main: "dist/index.js"
