#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn build

MODIFIED_DIST=$(git status --porcelain | grep " dist/index.js")

if [ -n "$MODIFIED_DIST" ]
then
  echo "Please commit changes to dist/index.js before pushing!"
  exit 1
fi
