#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn build

MODIFIED_DIST=$(git status --porcelain | grep " dist/index.js")

if [ -n "$MODIFIED_DIST" ]
then
  git add dist/index.js
  git commit --amend --no-edit --no-verify
fi
